# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = 'nexus'
  s.version = "0.1.0"

  s.authors = ["Nick Quaranto"]
  s.email = ['nick@quaran.to']

  s.description = 'Adds a command to RubyGems for uploading gems to a nexus server.'

  s.files = ["MIT-LICENSE", "Rakefile"]
  s.files += Dir['lib/**/*.rb']
  s.files += Dir['test/**/*.rb']

  s.homepage = 'http://sonatype.org/nexus'
  s.post_install_message = %q{
========================================================================

           Thanks for installing Nexus gem! You can now run:

    gem nexus          publish your gems onto Nexus server

========================================================================

}
  s.require_paths = ["lib"]
  s.summary = %q{Commands to interact with nexus server}

  s.add_runtime_dependency('always_verify_ssl_certificates', '~> 0.3.0')
  s.add_development_dependency('rake', '0.9.2.2')

  #s.add_runtime_dependency(%q<json_pure>, [">= 0"])
  #s.add_development_dependency(%q<shoulda>, [">= 0"])
  #s.add_development_dependency(%q<activesupport>, [">= 0"])
  #s.add_development_dependency(%q<webmock>, [">= 0"])
  #s.add_development_dependency(%q<rr>, [">= 0"])
end

